 channels:
     - conda-forge
 dependencies:
     - dlib
     - numpy
     - scipy
     - opencv
     - face_recognition
     - pandas==1.1.5
     - tensorflow-cpu==2.5.0
     - torch==1.8.1
     - tensorflow==2.4.0
     - imutils==0.5.4
     - plotly==4.14.3
     - retinaface==0.0.6
     - scikit_learn==0.24.2
     - streamlit==0.82.0
