 channels:
     - conda-forge
 dependencies:
     - dlib
     - numpy
     - scipy
     - opencv-python-headless
     - face_recognition
     - pandas
     - tensorflow-cpu
     - torch
     - tensorflow
     - imutils
     - plotly
     - retinaface
     - scikit_learn
     - streamlit
