 channels:
     - conda-forge
 dependencies:
     - dlib
     - numpy
     - scipy
     - face_recognition
     - pandas
     - imutils
     - plotly
     - streamlit
     - pip:
       - retinaface
       - opencv-python-headless
       - scikit_learn
       - tensorflow-cpu
       - torch
       
